# Generated by Django 5.1.3 on 2025-02-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_pics/8.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
